### ISSUE TITLE
xmlns attribute in the .csproj file causes no version information to be found

### ISSUE THREAD

**Issue by ebrown5-captioncall** [conficient/versionReaderTask#19]
Older versions of .csproj files have this attribute in the Project tag:
``` xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ```

When that tag is in my .csproj file, VersionReader doesn't find any version variables.

(I found this from a 4.7 project, editing the file over and over to find what was causing the failure.  I don't know how reproducible it actually is)

**Comment by conficient** [comment]
I'm not sure the tag is needed for 2017-format projects and later, so you should be able to remove it safely. It's adding an XML namespace to the project XML which prevents the xml code from reading the values correctly.

**Comment by ebrown5-captioncall** [comment]
It still compiles and the solution doesn't complain.  I worry it will be restored and break things unexpectedly.
________________________________

**Comment by conficient** [comment]
No further activity on this so closing..
