### ISSUE TITLE
Suggestion: Include package.json as a version information source 

### ISSUE THREAD

**Issue by ebrown5-captioncall** [conficient/versionReaderTask#20]
I use your versionReaderTask for my C# projects, and now that I have an angular project, I can't find any tool that will read the version property from the package.json file.

Looking at the code, it seems it wouldn't be too difficult to do by adapting "readProjectFile" to differentiate types, then reading package.json as an object - the "version" attribute is a top-level property there.

I'd be willing to do the work, but I'd want oversight so that my work fits in with your coding standards.

**Comment by conficient** [comment]
Thanks for the interest but I wasn't planning to support anything other than .NET projects. Feel free to create a new fork and rework it for `package.json` files though.
