### ISSUE TITLE
Update to new task handler

### ISSUE THREAD

**Issue by conficient** [conficient/versionReaderTask#6]
I have noticed in builds that the tool generates a warning
```
##[warning]Task 'VersionReaderTask' (1.15.0) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
```
It looks like I need to upgrade to use the new PS3 agent capability:
https://github.com/microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/README.md

I propose making this a version 2.0 change so that existing users of the tool do not have to upgrade unless they wish to do so (any 1.x upgrades are automatic).

**Comment by amirburbea** [comment]
Any update on this?

**Comment by conficient** [comment]
I had a brief look at it but had other more urgent issues to deal with. I also want to see if this can be fixed by solving #7 as well

**Comment by dshchupak** [comment]
@conficient Did you happen to have some time to look into this??

**Comment by conficient** [comment]
I took another look at this, and tried to pick up the node-based version 2 I started a while back. Just to say it helped remind me why I avoid node and javascript - it's an absolute trainwreck of configuration files, dependencies and builds. I'm walking away again for a while.

I tried a version2.0 using the step-by-step guide and the whole packaging process is broken.

Tried version 2.1 which uses a sample template but there are so many changes it's going to take too long to fix. I've pushed both branches up if anyone is interested in fixing them, but at present I have not got the time (or patience) to wade through this mess

**Comment by conficient** [comment]
Well I finally managed to get a Node version written, working and tested.

I even added support for a few more version variables. I've tested this on a test project for both Ubuntu and Windows builds in my test project: https://dev.azure.com/conficient/VersionReaderTaskTest/_build

Upgrade to version 2 (current is 2.2)
