### ISSUE TITLE
Add support for Linux build agents

### ISSUE THREAD

**Issue by boskjoett** [conficient/versionReaderTask#7]
This task fails on a Linux build agent.
Error:
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

Could you update it to support Linux build agents too?

**Comment by conficient** [comment]
Hmm.. not sure, I'll have a look at what methods exist for non-Windows build agents

**Comment by conficient** [comment]
From researching this, only Node and PowerShell are supported as task execution hosts. PowerShell Core exists for Linux I believe but it does not appear to be supported on Azure pipelines.

Hence it would mean a rewrite in Node which I really don't have time for right now, sorry.

**Comment by boskjoett** [comment]
I have found an alternate solution that might inspire you. I added a bash script task to my Azure Pipeline with these three lines of code:
```
export VERSION=`cat MyProject.csproj | grep -oPm1 "(?<=<Version>)[^<]+"`
echo "##vso[task.setvariable variable=VERSION]$VERSION"
echo Version read from project file: ${VERSION}
```

**Comment by conficient** [comment]
@boskjoett thanks for the pointer, I'll have a look.

**Comment by conficient** [comment]
Well I finally managed to get a Node version written, working and tested.

I even added support for a few more version variables. I've tested this on a test project for both Ubuntu and Windows builds in my test project: https://dev.azure.com/conficient/VersionReaderTaskTest/_build 

Upgrade to version 2 (current is 2.2)
